spring:
  groovy.template.check-template-location: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  redis:
    sentinel:
      master: redis
      nodes: localhost:26379

data:
  snapshot:
    storage:
      task.execution.pool:
        core-pool-size: 4
        max-pool-size: 16
        queue-capacity: 1000

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web: ERROR

sserver.tomcat.accesslog.enabled: true
